/**
 * Presentations Generation Plugin for DeepSeek Harness
 * AI auto-generate PPT - input topic and get complete presentation
 * From content organization to page layout
 * Suitable for reports, proposals, training, and roadshows
 */
export class PresentationsPlugin {
  name = 'presentations';
  description = 'PPT generation - create presentations from topics';
  
  constructor(ctx) {
    this.ctx = ctx;
    this.pptx = null;
  }

  async activate() {
    console.log('[Presentations Plugin] Activated');
  }

  async deactivate() {
    console.log('[Presentations Plugin] Deactivated');
  }

  async generatePresentation(options) {
    const { title, sections, style = 'professional' } = options;
    
    const presentation = {
      title: title || 'Presentation',
      style,
      slides: []
    };
    
    // Title slide
    presentation.slides.push({
      type: 'title',
      title: title || 'Presentation',
      subtitle: 'Generated by DeepSeek Harness',
      layout: 'title'
    });
    
    // Content slides
    if (sections && sections.length > 0) {
      for (const section of sections) {
        presentation.slides.push({
          type: 'content',
          title: section.title,
          content: section.content,
          bullets: section.bullets || [],
          layout: 'content'
        });
      }
    }
    
    // Summary slide
    presentation.slides.push({
      type: 'summary',
      title: 'Summary',
      content: 'Key takeaways and next steps',
      layout: 'summary'
    });
    
    // Thank you slide
    presentation.slides.push({
      type: 'thank-you',
      title: 'Thank You',
      content: 'Questions?',
      layout: 'thank-you'
    });
    
    return presentation;
  }

  async generateFromTopic(topic, slideCount = 10) {
    // Generate content based on topic
    const sections = this.generateSections(topic, slideCount);
    
    return await this.generatePresentation({
      title: topic,
      sections
    });
  }

  generateSections(topic, slideCount) {
    const sections = [];
    const sectionCount = Math.max(3, slideCount - 3); // Minus title, summary, thank you
    
    // Generate section titles based on topic
    const sectionTemplates = [
      { title: 'Introduction', content: `Overview of ${topic}` },
      { title: 'Background', content: `Context and background for ${topic}` },
      { title: 'Key Concepts', content: `Core concepts of ${topic}` },
      { title: 'Benefits', content: `Advantages of ${topic}` },
      { title: 'Implementation', content: `How to implement ${topic}` },
      { title: 'Case Studies', content: `Real-world examples of ${topic}` },
      { title: 'Challenges', content: `Common challenges with ${topic}` },
      { title: 'Best Practices', content: `Best practices for ${topic}` },
      { title: 'Future Trends', content: `Future of ${topic}` },
      { title: 'Conclusion', content: `Summary of ${topic}` }
    ];
    
    for (let i = 0; i < Math.min(sectionCount, sectionTemplates.length); i++) {
      sections.push(sectionTemplates[i]);
    }
    
    return sections;
  }

  async generateCorporatePresentation(options) {
    const { company, product, audience } = options;
    
    return await this.generatePresentation({
      title: `${company || 'Company'} - ${product || 'Product'} Presentation`,
      sections: [
        { title: 'Company Overview', content: `About ${company || 'our company'}` },
        { title: 'Product Introduction', content: `Introducing ${product || 'our product'}` },
        { title: 'Key Features', content: 'Main features and benefits' },
        { title: 'Market Opportunity', content: 'Target market and opportunity' },
        { title: 'Competitive Advantage', content: 'What sets us apart' },
        { title: 'Roadmap', content: 'Future plans and milestones' },
        { title: 'Call to Action', content: 'Next steps' }
      ]
    });
  }

  async generateTrainingPresentation(options) {
    const { topic, level, duration } = options;
    
    return await this.generatePresentation({
      title: `Training: ${topic || 'Topic'}`,
      sections: [
        { title: 'Learning Objectives', content: 'What you will learn' },
        { title: 'Prerequisites', content: 'What you need to know before' },
        { title: 'Core Concepts', content: 'Fundamental concepts' },
        { title: 'Hands-on Exercise', content: 'Practice what you learned' },
        { title: 'Advanced Topics', content: 'Deeper dive' },
        { title: 'Resources', content: 'Additional learning materials' },
        { title: 'Q&A', content: 'Questions and answers' }
      ]
    });
  }

  async generateSalesPresentation(options) {
    const { product, target, painPoints } = options;
    
    return await this.generatePresentation({
      title: `${product || 'Product'} Sales Deck`,
      sections: [
        { title: 'Problem', content: painPoints || 'Customer pain points' },
        { title: 'Solution', content: `How ${product || 'our product'} solves it` },
        { title: 'Features', content: 'Key features and benefits' },
        { title: 'Social Proof', content: 'Customer success stories' },
        { title: 'Pricing', content: 'Pricing options' },
        { title: 'ROI', content: 'Return on investment' },
        { title: 'Next Steps', content: 'How to get started' }
      ]
    });
  }

  async toPPTX(presentation) {
    const PptxGenJS = (await import('pptxgenjs')).default;
    const pptx = new PptxGenJS();
    
    // Set presentation properties
    pptx.author = 'DeepSeek Harness';
    pptx.company = 'DeepSeek';
    pptx.subject = presentation.title;
    pptx.title = presentation.title;
    
    // Apply style
    this.applyStyle(pptx, presentation.style);
    
    // Add slides
    for (const slide of presentation.slides) {
      const pptSlide = pptx.addSlide();
      
      switch (slide.type) {
        case 'title':
          this.addTitleSlide(pptSlide, slide);
          break;
        case 'content':
          this.addContentSlide(pptSlide, slide);
          break;
        case 'summary':
          this.addSummarySlide(pptSlide, slide);
          break;
        case 'thank-you':
          this.addThankYouSlide(pptSlide, slide);
          break;
      }
    }
    
    return await pptx.write({ outputType: 'nodebuffer' });
  }

  applyStyle(pptx, style) {
    switch (style) {
      case 'professional':
        pptx.theme = { headColor: '003366', bodyColor: '333333' };
        break;
      case 'modern':
        pptx.theme = { headColor: '0066CC', bodyColor: '444444' };
        break;
      case 'minimalist':
        pptx.theme = { headColor: '222222', bodyColor: '555555' };
        break;
      default:
        pptx.theme = { headColor: '003366', bodyColor: '333333' };
    }
  }

  addTitleSlide(slide, data) {
    slide.addText(data.title, {
      x: 0.5,
      y: 1.5,
      w: '90%',
      fontSize: 32,
      bold: true,
      color: '003366',
      align: 'center'
    });
    
    slide.addText(data.subtitle || '', {
      x: 0.5,
      y: 2.5,
      w: '90%',
      fontSize: 18,
      color: '666666',
      align: 'center'
    });
  }

  addContentSlide(slide, data) {
    slide.addText(data.title, {
      x: 0.5,
      y: 0.5,
      w: '90%',
      fontSize: 24,
      bold: true,
      color: '003366'
    });
    
    if (data.bullets && data.bullets.length > 0) {
      slide.addText(
        data.bullets.map(bullet => ({ text: bullet, options: { bullet: true } })),
        {
          x: 0.5,
          y: 1.5,
          w: '90%',
          fontSize: 16,
          color: '333333'
        }
      );
    } else {
      slide.addText(data.content, {
        x: 0.5,
        y: 1.5,
        w: '90%',
        fontSize: 16,
        color: '333333'
      });
    }
  }

  addSummarySlide(slide, data) {
    slide.addText(data.title, {
      x: 0.5,
      y: 0.5,
      w: '90%',
      fontSize: 24,
      bold: true,
      color: '003366'
    });
    
    slide.addText(data.content, {
      x: 0.5,
      y: 1.5,
      w: '90%',
      fontSize: 16,
      color: '333333'
    });
  }

  addThankYouSlide(slide, data) {
    slide.addText(data.title, {
      x: 0.5,
      y: 1.5,
      w: '90%',
      fontSize: 32,
      bold: true,
      color: '003366',
      align: 'center'
    });
    
    slide.addText(data.content, {
      x: 0.5,
      y: 2.5,
      w: '90%',
      fontSize: 18,
      color: '666666',
      align: 'center'
    });
  }

  async toHTML(presentation) {
    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${presentation.title}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 0; padding: 20px; }
    .slide { border: 1px solid #ccc; margin: 20px 0; padding: 40px; page-break-after: always; }
    .title { font-size: 24px; font-weight: bold; margin-bottom: 20px; }
    .content { font-size: 16px; }
    .bullet { margin: 10px 0; }
  </style>
</head>
<body>
  <h1>${presentation.title}</h1>
`;
    
    for (const slide of presentation.slides) {
      html += `  <div class="slide">
    <div class="title">${slide.title}</div>
    <div class="content">
`;
      
      if (slide.bullets && slide.bullets.length > 0) {
        for (const bullet of slide.bullets) {
          html += `      <div class="bullet">• ${bullet}</div>
`;
        }
      } else {
        html += `      <p>${slide.content}</p>
`;
      }
      
      html += `    </div>
  </div>
`;
    }
    
    html += `</body>
</html>`;
    
    return html;
  }
}

export default PresentationsPlugin;
